version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        - CASHFREE_BASE_URL=${CASHFREE_BASE_URL}
        - CASHFREE_SECRET_KEY_PROD=${CASHFREE_SECRET_KEY_PROD}
        - CASHFREE_APP_ID_PROD=${CASHFREE_APP_ID_PROD}
        - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
        - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
        - SPACES_KEY=${SPACES_KEY}
        - SPACES_SECRET=${SPACES_SECRET}
        - NEXT_PUBLIC_SPACE_NAME=${NEXT_PUBLIC_SPACE_NAME}
        - NEXT_PUBLIC_SPACES_REGION=${NEXT_PUBLIC_SPACES_REGION}
        - SPACE_NAME=${SPACE_NAME}
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - CASHFREE_BASE_URL=${CASHFREE_BASE_URL}
      - CASHFREE_SECRET_KEY_PROD=${CASHFREE_SECRET_KEY_PROD}
      - CASHFREE_APP_ID_PROD=${CASHFREE_APP_ID_PROD}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - SPACES_KEY=${SPACES_KEY}
      - SPACES_SECRET=${SPACES_SECRET}
      - NEXT_PUBLIC_SPACE_NAME=${NEXT_PUBLIC_SPACE_NAME}
      - NEXT_PUBLIC_SPACES_REGION=${NEXT_PUBLIC_SPACES_REGION}
      - SPACE_NAME=${SPACE_NAME}
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 700M